[build]
  command = "./build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_TELEMETRY_DISABLED = "1"
  GO_SKIP_INSTALL = "true"
  GIT_LFS_SKIP_SMUDGE = "1"

# Run hooks before build stages
[build.lifecycle]
  onPreBuild = "source ./netlify/build-hooks/pre-build.sh"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 